apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-model
  template:
    metadata:
      labels:
        app: ai-model
    spec:
      containers:
      - name: ai-model
        image: <your-acr-name>.azurecr.io/ai-model:v1
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
        - containerPort: 80
